language: rust
rust:
  - stable
services:
  - docker
before_install:
  - docker pull polyverse/rust-dev-env
script:
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo clippy
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo test
  - docker run -v cargo-cache:/root/.cargo/registry -v $PWD:/volume --rm -t polyverse/rust-dev-env cargo build --release
deploy:
# Be sure to add a GITHUB_TOKEN environment variable in this job's config
# which the "Public Repos" permission, to enable pushing releases.
  - provider: releases
    file:
      - "target/x86_64-unknown-linux-musl/release/zerotect"
      - "reference/schema.json"
      - "reference/zerotect.toml"
      - "install/install.sh"
    skip_cleanup: true
    on:
      tags: true
    edge: true