language: rust
rust:
  - stable
services:
  - docker
before_install:
  - docker pull clux/muslrust
script:
  - docker run -v $PWD:/volume --rm -t clux/muslrust cargo test
  - docker run -v $PWD:/volume --rm -t clux/muslrust cargo build --release
deploy:
  provider: releases
  file:
    - "target/x86_64-unknown-linux-musl/release/polytect"
    - "install/systemd/systemd-install.sh"
  skip_cleanup: true
  on:
    tags: true
  edge: true
