language: rust
rust:
  - stable
env:
  - PKG_CONFIG_ALLOW_CROSS=1
addons:
  apt:
    packages: musl-tools
cache:
  cargo: true
  directories:
    - openssl
before_install:
  - rustup target add x86_64-unknown-linux-musl
  - cd $HOME
  - git clone git://git.openssl.org/openssl.git
  - cd $HOME/openssl
  - ./config -fPIC --prefix=$HOME/openssl_install --openssldir=$HOME/openssl_install/ssl
  - make
  - make install
script:
  - cargo build --release --target x86_64-unknown-linux-musl
deploy:
  provider: releases
  file: "target/x86_64-unknown-linux-musl/release/polytect"
  skip_cleanup: true
  on:
    tags: true
  edge: true
