language: rust
rust:
  - stable
addons:
  apt:
    packages: musl-tools libssl-dev
before_install:
  - rustup target add x86_64-unknown-linux-musl
script:
  - cargo build --release --target x86_64-unknown-linux-musl
deploy:
  provider: releases
  file: "target/x86_64-unknown-linux-musl/release/polytect"
  skip_cleanup: true
  on:
    tags: true
  edge: true
