language: rust
rust:
  - stable
env:
  - PKG_CONFIG_ALLOW_CROSS=1
addons:
  apt:
    packages: musl-tools
before_install:
  - rustup target add x86_64-unknown-linux-musl
  - git clone git://git.openssl.org/openssl.git
  - cd openssl
  - ./config -fPIC --prefix=/usr/local --openssldir=/usr/local/ssl
  - make
  - make install
script:
  - cargo build --release --target x86_64-unknown-linux-musl
deploy:
  provider: releases
  file: "target/x86_64-unknown-linux-musl/release/polytect"
  skip_cleanup: true
  on:
    tags: true
  edge: true
