[package]
name = "zerotect"
version = "0.4.13"
authors = ["Archis Gore <archis@polyverse.io>"]
edition = "2018"

[dependencies]
log = "0.4.11"
sys-info = "0.7.0"
sysctl = "0.4.0"
strum = "0.20.0"
strum_macros = "0.20.1"
regex = "1"
enum-display-derive = "0.1.0"
num = "0.3.1"
lazy_static = "1.4.0"
num-traits = "0.2"
num-derive = "0.3.3"
timeout-iterator = { version = "1.0.0", features = ["async"] }
serde = { version = "1.0.118", features = ["derive", "rc"] }
serde_json = { version = "1.0.60", features = ["arbitrary_precision"]}
toml = "0.5.8"
http = "0.2.2"
rmesg = {version = "1.0.3", features = ["async", "ptr"]}
libflate = "1.0.3"
rust-cef-derive = "0.2.0"
rust-cef = "0.2.0"
syslog = "5.0.0"
libc = "0.2.81"
file-rotate-record-boundary = "0.3.0"
futures = "0.3.8"
pagerduty-rs = {version = "0.1.0", features = ["async"] }
time = {version = "0.2.23", features = ["std", "serde"] }
hyper = { version = "0.14.1", optional = true }
hyper-tls = {version = "0.4.3", optional = true}
async-trait = "0.1.42"
tokio = { version = "1.0.0", features = ["rt", "macros", "time"] }

[dependencies.clap]
version = "2.33.3"
# Disable all features - just minimal brutal args parsing
default-features = false

[dev-dependencies]
assert_matches = "1.4.0"
rand = "0.8.0"
schemars = { version = "0.8.0" }
pretty_assertions = "0.6.1"

# Enable LTO for release (since it only builds in Travis and doesn't block day to day)
[profile.release]
lto = "fat"
codegen-units = 1
