[package]
name = "polytect"
version = "0.1.0"
authors = ["Archis Gore <archis@polyverse.io>"]
edition = "2018"

[dependencies]
sys-info = "0.6.0"
sysctl = "0.4.0"
strum = "0.18.0"
strum_macros = "0.18.0"
regex = "1"
typename = "0.1.2"
enum-display-derive = "0.1.0"
num = "0.2"
lazy_static = "1.4.0"
num-traits = "0.2"
num-derive = "0.3.0"
timeout-iterator = "0.2.0"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = { version = "1.0.51", features = ["arbitrary_precision"]}
reqwest = { version = "0.10.4", features = ["json"] }
chrono = { version = "0.4", features = ["serde"] }
schemars = { version = "0.7.0", features = ["chrono"]}
futures = "0.3.4"
pretty_assertions = "0.6.1"

[dependencies.clap]
version = "2.33.0"
default-features = false

# Cherry-pick the features you'd like to use
features = [ "suggestions", "color", "vec_map", "wrap_help" ]