[package]
name = "zerotect"
version = "0.4.10"
authors = ["Archis Gore <archis@polyverse.io>"]
edition = "2018"

[dependencies]
log = "0.4.11"
sys-info = "0.7.0"
sysctl = "0.4.0"
strum = "0.19.5"
strum_macros = "0.19.4"
regex = "1"
enum-display-derive = "0.1.0"
num = "0.3.0"
lazy_static = "1.4.0"
num-traits = "0.2"
num-derive = "0.3.2"
timeout-iterator = "0.5.0"
serde = { version = "1.0.116", features = ["derive", "rc"] }
serde_json = { version = "1.0.58", features = ["arbitrary_precision"]}
chrono = { version = "0.4", features = ["serde", "std"] }
toml = "0.5.6"
http = "0.2.1"
rmesg = "0.8.0"
libflate = "1.0.2"
rust-cef-derive = "0.1.3"
rust-cef = "0.1.3"
syslog = "5.0.0"
libc = "0.2.79"
file-rotate-record-boundary = "0.3.0"
ureq = "1.5.0"

[dependencies.clap]
version = "2.33.3"
# Disable all features - just minimal brutal args parsing
default-features = false

[dev-dependencies]
assert_matches = "1.4.0"
rand = "0.7.3"
schemars = { version = "0.8.0", features = ["chrono"]}
pretty_assertions = "0.6.1"

# Enable LTO for release (since it only builds in Travis and doesn't block day to day)
[profile.release]
lto = "fat"
codegen-units = 1

