[package]
name = "polytect"
version = "0.1.0"
authors = ["Archis Gore <archis@polyverse.io>"]
edition = "2018"

[dependencies]
sys-info = "~0.5.7"
sysctl = "0.4.0"
chrono = "0.4"
strum = "0.15.0"
strum_macros = "0.15.0"

[dependencies.clap]
version = "~2.33"
default-features = false

# Cherry-pick the features you'd like to use
features = [ "suggestions", "color", "vec_map", "wrap_help" ]