[package]
name = "zerotect"
version = "0.1.0"
authors = ["Archis Gore <archis@polyverse.io>"]
edition = "2018"

[dependencies]
log = "0.4.11"
sys-info = "0.7.0"
sysctl = "0.4.0"
strum = "0.19.2"
strum_macros = "0.19.2"
regex = "1"
typename = "0.1.2"
enum-display-derive = "0.1.0"
num = "0.3.0"
lazy_static = "1.4.0"
num-traits = "0.2"
num-derive = "0.3.1"
timeout-iterator = "0.5.0"
serde = { version = "1.0.115", features = ["derive", "rc"] }
serde_json = { version = "1.0.57", features = ["arbitrary_precision"]}
reqwest = { version = "0.10.7", features = ["json", "blocking", "gzip", "brotli"] }
chrono = { version = "0.4", features = ["serde"] }
schemars = { version = "0.7.6", features = ["chrono"]}
pretty_assertions = "0.6.1"
toml = "0.5.6"
rand = "0.7.3"
http = "0.2.1"
rmesg = "0.6.0"
libflate = "1.0.2"
rust-cef-derive = "0.0.7"
rust-cef = "0.0.5"
fern = "0.6.0"
syslog = "5.0.0"
libc = "0.2.74"
file-rotate-record-boundary = "0.3.0"

[dependencies.clap]
version = "2.33.3"
default-features = false

# Cherry-pick the features you'd like to use
features = [ "suggestions", "color", "vec_map", "wrap_help" ]

# Enable LTO for release (since it only builds in Travis and doesn't block day to day)
[profile.release]
lto = true
