[package]
name = "polytect"
version = "0.1.0"
authors = ["Archis Gore <archis@polyverse.io>"]
edition = "2018"

[dependencies]
sys-info = "0.5.8"
sysctl = "0.4.0"
strum = "0.15.0"
strum_macros = "0.15.0"
regex = "1"
typename = "0.1.1"
enum-display-derive = "0.1.0"
num = "0.2"
lazy_static = "1.4.0"
num-traits = "0.2"
num-derive = "0.2"
timeout-iterator = "0.1.0"

[dependencies.clap]
version = "2.33.0"
default-features = false

# Cherry-pick the features you'd like to use
features = [ "suggestions", "color", "vec_map", "wrap_help" ]