verbosity = 0

[auto_configure]
exception_trace = true
fatal_signals = true
klog_include_timestamp = true

[monitor_config]
gobble_old_events = false

[console_config]
format = 'Text'

[polycorder_config]
auth_key = 'AuthKeyFromPolyverseAccountManager'
node_id = 'UsefulNodeIdentifierToGroupEvents'
flush_event_count = 10

[polycorder_config.flush_timeout]
secs = 10
nanos = 0
